import enum
 

class Vietnamese(enum.Enum):
    INCOME_SECTION = 'Mục thu'
    EXPENSE_SECTION = 'Mục chi'
    INCOME = 'Thu'
    EXPENSE = 'Chi'
    OK = 'OK'
    ADD = 'Thêm'
    SAVE = 'Lưu'
    CANCEL = 'Huỷ'
    MONTH = 'Tháng'
    YEAR = 'Năm'
    CONTENT = 'Nội dung'
    AMOUNT_OF_MONEY = 'Số tiền'
    DATE = 'Ngày'
    ADD_INCOME = 'Thêm thu'
    EDIT_INCOME = 'Sửa thu'
    ADD_EXPENSE = 'Thêm chi'
    EDIT_EXPENSE = 'Sửa chi'
    MUST_HAVE = 'Bắt buộc trả'
    NICE_TO_HAVE = 'Cải thiện cuộc sống'
    WASTED = 'Tiêu hoang'
    REVENUE_AND_EXPENDITURE_SOFTWARE = 'Phần mềm thu chi'
    EXPENSE_TYPE = 'Loại chi tiêu'
    TOTAL = 'Tổng cộng'
    LAST_MONTH = 'Tháng trước'
    THIS_MONTH = 'Tháng này'
    STANDARD_LIVING = 'Mức sống tiêu chuẩn'
    MINIUM_STANDARD_LIVING = 'Mức sống tối thiểu'
    EXPENSE_IN_MONTH = 'Chi tiêu trong tháng'
